version: '3.8'

services:
  db:
    image: postgres:15
    container_name: banke-postgres
    restart: always
    environment:
      POSTGRES_DB: bankapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: banke-app
    restart: always
    ports:
      - "5252:5252"
    env_file:
      - .env.prod
    depends_on:
      - db
